name: CI-creation-release

on:
  workflow_dispatch:
    inputs:
      tag-type:
        type: choice
        description: 'Tipo de Tag'
        required: true
        options:
          - Major
          - Minor
          - Patch

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    environment:
      name: develop

    steps:

      - name: Print inputs
        run: |
          echo "tag-type: ${{ github.event.inputs.tag-type }}" 


      - name: Set tag type to Major
        if: github.event.inputs.tag-type == 'Major'
        run: |
          echo "tag_type_action=incrementMajor" >> $GITHUB_ENV

      - name: Set tag type to Minor
        if: github.event.inputs.tag-type == 'Minor'
        run: |
          echo "tag_type_action=incrementMinor" >> $GITHUB_ENV

      - name: Set tag type to Patch
        if: github.event.inputs.tag-type == 'Patch'
        run: |
          echo "tag_type_action=incrementPatch" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle calculate tag version
        run: |
          ./gradlew release -Prelease.versionIncrementer=${{ env.tag_type_action }} -Prelease.localOnly
          TAG_VERSION=$(./gradlew cV -q -Prelease.quiet)
          echo "::set-output name=TAG_VERSION::$TAG_VERSION"
        id: calculate_tag_version

      - name: Print calculate_tag_version
        run: |
          echo "calculate_tag_version: ${{ steps.calculate_tag_version.outputs.TAG_VERSION }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.calculate_tag_version.outputs.TAG_VERSION }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Execute Gradle publish
        run: |
          ./gradlew publish
          -PnexusUserName=${{ secrets.NEXUSUSERNAME }}
          -PnexusPassword=${{ secrets.NEXUSPASSWORD }}
          -PnexusMavenRepo=${{ secrets.NEXUSMAVENREPO }}
          -PnexusReleasesRepoUrl=${{ secrets.NEXUSRELEASESREPOURL }}
          -PnexusSnapshotsRepoUrl=${{ secrets.NEXUSSNAPSHOTSREPOURL }}
