name: CI-Tag

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'
        required: true
        default: 'master'

jobs:
  print-inputs:
    runs-on: ubuntu-latest

    environment:
      name: develop

    steps:
      - run: |
          echo "Env: ${{ github.event.inputs.environment }}" 
          echo "Branch: ${{ github.event.inputs.branch }}"
