name: CI

on:
  push:
    branches: [ 'master' ]
    tags: [ v* ]
  pull_request:
    branches: [ '**' ]

jobs:
  send-notification:
    runs-on: ubuntu-latest

    environment:
      name: develop

    steps:
      - uses: actions/checkout@v3

      - uses: 8BitJonny/gh-get-current-pr@1.4.0
        name: Get current pull request
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Print variables
        run: |
          echo "Variable (steps.PR.outputs.pr_url): ${{ steps.PR.outputs.pr_url }}"
          echo "Variable (github.event.pull_request.draft): ${{ github.event.pull_request.draft }}"
          echo "Variable (steps.PR.outputs.pr_labels): ${{ steps.PR.outputs.pr_labels }}"

      - name: Invoke chat hook 2
        uses: joelwmale/webhook-action@master
        if: success() && steps.PR.outputs.pr_url && github.event.pull_request.draft == false && contains(steps.PR.outputs.pr_labels, 'notification')
        with:
          url: ${{ secrets.WEBHOOK_CHAT_URL }}
          body: '{"text": "[${{ steps.PR.outputs.pr_labels }}] PR (${{ steps.PR.outputs.pr_title }}) ${{ steps.PR.outputs.pr_url }} por ${{ github.actor }}"}'

  print-release-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Print release variables
        run: |
          echo "Variable (github.event_namel): ${{ github.event_name }}"
          echo "Variable (github.ref): ${{ github.ref }}"
          echo "Variable (github.repository): ${{ github.repository }}"
          echo "Variable (github.event.commits.*.message): ${{ github.event.commits.*.message }}"

  release:
    runs-on: ubuntu-latest

    needs: ['send-notification', 'print-release-variables']

    if: github.event_name == 'push'
      && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
      && github.repository == 'josue270193/test_version'
      && !contains(toJSON(github.event.commits.*.message), '[skip release]')

    steps:
      - name: Check out code
        uses: actions/checkout@v3 # https://github.com/actions/checkout
        with:
          fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci

      - name: Build and release
        run: ./gradlew githubRelease releaseSummary
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


