name: create_pr

on:
  pull_request:
    branches: [ develop, qa, master ]

jobs:
  send-notification:

    runs-on: ubuntu-latest

    environment:
      name: develop

    steps:
      - uses: actions/checkout@v3

      - uses: 8BitJonny/gh-get-current-pr@1.4.0
        name: Get current pull request
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Print variables
        run: |
          echo "Variable (github.event.label): ${{ github.event.label }}"
          echo "Variable (github.event.label.name): ${{ github.event.label.name }}"
          echo "Variable (steps.PR.outputs.pr_url): ${{ steps.PR.outputs.pr_url }}"
          echo "Variable (steps.PR.outputs.pr_labels): ${{ steps.PR.outputs.pr_labels }}"
          echo "Variable (github.event.pull_request.draft): ${{ github.event.pull_request.draft }}"

      - name: Invoke chat hook 2
        uses: joelwmale/webhook-action@master
        if: steps.PR.outputs.pr_url && github.event.pull_request.draft == false && contains(${{ steps.PR.outputs.pr_labels }}, 'notification')
        with:
          url: ${{ secrets.WEBHOOK_CHAT_URL }}
          body: '{"text": "[${{ steps.PR.outputs.pr_labels }}] PR (${{ steps.PR.outputs.pr_title }}) ${{ steps.PR.outputs.pr_url }} por ${{ github.actor }}"}'


